### PR TITLE
Replaced Organizer interest form with pre-registration button & link

### LINKED ISSUE #25: Add pre-registration link
- [x] Create a button/link in front of the committee interest form
- [x] Use this link: https://forms.gle/F7mTHdNWymW8km7z5
- [x] Style Register button according to new design.

### PR DESCRIPTION
**Pull request by aryasalian**
This should resolve #25 from the Projects tab. From the comments written in the code, I'm assuming this task was to replace the organiser interest form with the pre-registration link. If not, LMK what needs to be done.

### CODE REVIEW

**Review by atoneyd — CHANGES_REQUESTED** [review]
Actually, the organizer interest form should still be there; it can go after the hacker interest form. We will remove it sometime in the fall. Sorry for the confusion!

**Comment by aryasalian** [comment]
> Actually, the organizer interest form should still be there; it can go after the hacker interest form. We will remove it sometime in the fall. Sorry for the confusion!

Alright, no problem! Let me fix it right up.

**Comment by aryasalian** [comment]
How about now @atoneyd?

**Review by atoneyd — CHANGES_REQUESTED** [review]
One more small thing: could you add target="_blank" to both links so that they open up in a new tab?

**Comment by aryasalian** [comment]
> One more small thing: could you add target="_blank" to both links so that they open up in a new tab?

One small question, why do we need the anchor tag named .apply at lines 85 and 87?

**Comment by aryasalian** [comment]
NVM got it, it's for mobile view my bad!

**Comment by atoneyd** [comment]
yeah, the class naming is kinda bad

**Comment by aryasalian** [comment]
Done, can you check it?

**Review by atoneyd — APPROVED** [review]
LGTM, thanks!

**Comment by aryasalian** [comment]
Alright!

**Pull request merged**
