### PR TITLE
Countdown Timer

### LINKED ISSUE #3: Add countdown timer
- [x] Add to title section, below dates
- [x] Can look at previous one for inspo (2022 repository) , or look up sample code

### PR DESCRIPTION
**Pull request by jadekeegan**
This pull request adds the countdown timer Javascript to the website. The countdown has been added to the site, but the styling is very minimal as it will be changed in a future PR to align with the redesigned site.

## Major Changes
- Added the `countdown.js` file which contains the JS for the countdown.
- Added the countdown to the root `index.html` file and added a few lines of to the `main.css` file to style the added HTML.

>This PR resolves issue #3.

### CODE REVIEW

**Review by atoneyd — APPROVED** [review]
LGTM :D

**Comment by aryasalian** [comment]
@atoneyd @jadekeegan Hey guys I know this PR is closed but I just checked the website and I think we should put an @media rule for mobile view to make the countdown align: center instead of left when the viewport decreases, otherwise it looks really off. I wouldn't mind solving it on my own if a new issue is raised.

**Comment by jadekeegan** [comment]
> @atoneyd @jadekeegan Hey guys I know this PR is closed but I just checked the website and I think we should put an @media rule for mobile view to make the countdown align: center instead of left when the viewport decreases, otherwise it looks really off. I wouldn't mind solving it on my own if a new issue is raised.

Hey! Since I am redesigning the format of the website quite a bit, I didn't want to add too much styling to the countdown on the current format after I did the initial styling since it will be changed depending on what looks good for the new format. The mobile view is definitely on my radar though! Thank you for checking in on this!

**Comment by aryasalian** [comment]
Alright that makes sense. Sounds good to me!

**Pull request merged**
